[versions]
aboutlibraries = "13.2.1"
accompanist = "0.37.3"
activity = "1.12.3"
agp = "9.0.0"
androidx-annotation = "1.9.1"
androidx-sqlite = "2.6.2"
appcompat = "1.7.1"
browser = "1.9.0"
buildconfig = "6.0.7"
circuit = "0.32.0"
coil = "3.3.0"
compose-hot-reload = "1.1.0-alpha04"
compose-multiplatform = "1.10.0"
compose-unstyled = "1.49.6"
core-ktx = "1.17.0"
datastore = "1.2.0"
decompose = "3.4.0"
desugar = "2.1.5"
detekt = "2.0.0-alpha.2"
detekt-compose = "0.5.6"
directories = "26"
emoji2 = "1.6.0"
essenty = "2.5.0"
glance = "1.1.1"
hanekokoro-framework = "0.2.2"
kermit = "2.0.8"
kotest = "6.0.7"
kotlin = "2.3.0"
kotlinx-coroutines = "1.10.2"
kotlinx-datetime = "0.7.1"
kotlinx-serialization = "1.10.0"
kover = "0.9.5"
krop = "0.2.0"
ksp = "2.3.5"
ktlint = "1.8.0"
ktlint-gradle = "14.0.1"
lifecycle = "2.10.0"
material3-adaptive = "1.2.0"
material3-multiplatform = "1.10.0-alpha05"
metro = "0.10.2"
molecule = "2.2.0"
okio = "3.16.4"
paging = "3.4.0"
preference = "1.2.1"
proguard = "7.8.2"
robolectric = "4.16.1"
sharetarget = "1.2.0"
splashscreen = "1.2.0"
sqldelight = "2.2.1"
startup = "1.2.0"
turbine = "1.2.1"
uri = "0.0.21"

[libraries]
# JVM Only
directories = { group = "dev.dirs", name = "directories", version.ref = "directories" }

# Android Only
accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist" }

# AndroidX (Android Only)
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-browser = { group = "androidx.browser", name = "browser", version.ref = "browser" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
androidx-emojipicker = { group = "androidx.emoji2", name = "emoji2-emojipicker", version.ref = "emoji2" }
androidx-sharetarget = { group = "androidx.sharetarget", name = "sharetarget", version.ref = "sharetarget" }
androidx-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "splashscreen" }
androidx-sqlite-framework = { group = "androidx.sqlite", name = "sqlite-framework", version.ref = "androidx-sqlite" }
androidx-startup = { group = "androidx.startup", name = "startup-runtime", version.ref = "startup" }

# AndroidX (Multiplatform)
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "androidx-annotation" }
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }
androidx-preference = { group = "androidx.preference", name = "preference", version.ref = "preference" }

# CMP Dependencies
compose-components-preview = { group = "org.jetbrains.compose.components", name = "components-ui-tooling-preview", version.ref = "compose-multiplatform" }
compose-components-resources = { group = "org.jetbrains.compose.components", name = "components-resources", version.ref = "compose-multiplatform" }
compose-foundation = { group = "org.jetbrains.compose.foundation", name = "foundation", version.ref = "compose-multiplatform" }
compose-material-ripple = { group = "org.jetbrains.compose.material", name = "material-ripple", version.ref = "compose-multiplatform" }
compose-material3 = { group = "org.jetbrains.compose.material3", name = "material3", version.ref = "material3-multiplatform" }
compose-material3-adaptive = { group = "org.jetbrains.compose.material3.adaptive", name = "adaptive", version.ref = "material3-adaptive" }
compose-preview = { group = "org.jetbrains.compose.ui", name = "ui-tooling-preview", version.ref = "compose-multiplatform" }
compose-runtime = { group = "org.jetbrains.compose.runtime", name = "runtime", version.ref = "compose-multiplatform" }
compose-ui = { group = "org.jetbrains.compose.ui", name = "ui", version.ref = "compose-multiplatform" }
compose-ui-tooling = { group = "org.jetbrains.compose.ui", name = "ui-tooling", version.ref = "compose-multiplatform" }

# Jetpack Glance
androidx-glance = { group = "androidx.glance", name = "glance", version.ref = "glance" }
androidx-glance-appwidget = { group = "androidx.glance", name = "glance-appwidget", version.ref = "glance" }
androidx-glance-appwidget-preview = { group = "androidx.glance", name = "glance-appwidget-preview", version.ref = "glance" }
androidx-glance-material3 = { group = "androidx.glance", name = "glance-material3", version.ref = "glance" }
androidx-glance-preview = { group = "androidx.glance", name = "glance-preview", version.ref = "glance" }

# AndroidX Paging
androidx-paging-common = { group = "androidx.paging", name = "paging-common", version.ref = "paging" }
androidx-paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "paging" }

# KotlinX
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-serialization-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "kotlinx-serialization" }

# Decompose + Hanekokoro Framework
decompose = { group = "com.arkivanov.decompose", name = "decompose", version.ref = "decompose" }
decompose-compose = { group = "com.arkivanov.decompose", name = "extensions-compose", version.ref = "decompose" }
decompose-compose-experimental = { group = "com.arkivanov.decompose", name = "extensions-compose-experimental", version.ref = "decompose" }
decompose-jetpack = { group = "com.arkivanov.decompose", name = "jetpack-component-context", version.ref = "decompose" }
essenty-backhandler = { group = "com.arkivanov.essenty", name = "back-handler", version.ref = "essenty" }
essenty-coroutines = { group = "com.arkivanov.essenty", name = "lifecycle-coroutines", version.ref = "essenty" }
hanekokoro-framework-annotations = { group = "io.github.shadowrz.hanekokoro.framework", name = "annotations", version.ref = "hanekokoro-framework" }
hanekokoro-framework-codegen = { group = "io.github.shadowrz.hanekokoro.framework", name = "codegen", version.ref = "hanekokoro-framework" }
hanekokoro-framework-integration = { group = "io.github.shadowrz.hanekokoro.framework", name = "integration", version.ref = "hanekokoro-framework" }
hanekokoro-framework-markers = { group = "io.github.shadowrz.hanekokoro.framework", name = "markers", version.ref = "hanekokoro-framework" }
hanekokoro-framework-runtime = { group = "io.github.shadowrz.hanekokoro.framework", name = "runtime", version.ref = "hanekokoro-framework" }

# AboutLibraries
aboutlibraries-compose-material3 = { group = "com.mikepenz", name = "aboutlibraries-compose-m3", version.ref = "aboutlibraries" }
aboutlibraries-core = { group = "com.mikepenz", name = "aboutlibraries-core", version.ref = "aboutlibraries" }

# Coil
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-core = { group = "io.coil-kt.coil3", name = "coil-core", version.ref = "coil" }
coil-gif = { group = "io.coil-kt.coil3", name = "coil-gif", version.ref = "coil" }

# General KMP / CMP Libraries
circuit-sharedelements = { group = "com.slack.circuit", name = "circuit-sharedelements", version.ref = "circuit" }
composeunstyled-primitives = { group = "com.composables", name = "composeunstyled-primitives", version.ref = "compose-unstyled" }
kermit = { group = "co.touchlab", name = "kermit", version.ref = "kermit" }
krop-core = { group = "com.attafitamim.krop", name = "core", version.ref = "krop" }
metro-runtime = { group = "dev.zacsweers.metro", name = "runtime", version.ref = "metro" }
okio = { group = "com.squareup.okio", name = "okio", version.ref = "okio" }
okio-fakefilesystem = { group = "com.squareup.okio", name = "okio-fakefilesystem", version.ref = "okio" }
uri = { group = "com.eygraber", name = "uri-kmp", version.ref = "uri" }

# SQLDelight
sqldelight-android = { group = "app.cash.sqldelight", name = "android-driver", version.ref = "sqldelight" }
sqldelight-coroutines = { group = "app.cash.sqldelight", name = "coroutines-extensions", version.ref = "sqldelight" }
sqldelight-jvm = { group = "app.cash.sqldelight", name = "sqlite-driver", version.ref = "sqldelight" }
sqldelight-runtime = { group = "app.cash.sqldelight", name = "runtime", version.ref = "sqldelight" }

# Testing
## Molecule is only used to test presenters
molecule-runtime = { group = "app.cash.molecule", name = "molecule-runtime", version.ref = "molecule" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }

# Kotest
kotest-assertions = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }
kotest-framework-engine = { group = "io.kotest", name = "kotest-framework-engine", version.ref = "kotest" }
kotest-runner-junit5 = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "kotest" }

# Codestyle dependencies
detekt-compose = { group = "io.nlopez.compose.rules", name = "detekt", version.ref = "detekt-compose" }

# Build support
desugar = { group = "com.android.tools", name = "desugar_jdk_libs_nio", version.ref = "desugar" }

# Placeholders for Renovate
ktlint-cli = { group = "com.pinterest.ktlint", name = "ktlint-cli", version.ref = "ktlint" }
proguard-gradle = { group = "com.guardsquare", name = "proguard-gradle", version.ref = "proguard" }

# Convention plugins dependencies
android-gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
compose-compiler-plugin = { group = "org.jetbrains.kotlin", name = "compose-compiler-gradle-plugin", version.ref = "kotlin" }
compose-multiplatform-plugin = { group = "org.jetbrains.compose", name = "org.jetbrains.compose.gradle.plugin", version.ref = "compose-multiplatform" }
detekt-plugin = { group = "dev.detekt", name = "dev.detekt.gradle.plugin", version.ref = "detekt" }
kotest-plugin = { group = "io.kotest", name = "io.kotest.gradle.plugin", version.ref = "kotest" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kover-plugin = { group = "org.jetbrains.kotlinx.kover", name = "org.jetbrains.kotlinx.kover.gradle.plugin", version.ref = "kover" }
ksp-plugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
ktlint-plugin = { group = "org.jlleitschuh.gradle.ktlint", name = "org.jlleitschuh.gradle.ktlint.gradle.plugin", version.ref = "ktlint-gradle" }
metro-gradle-plugin = { group = "dev.zacsweers.metro", name = "dev.zacsweers.metro.gradle.plugin", version.ref = "metro" }

[plugins]
# Plugins already present in plugin classpath
android-multiplatform = { id = "com.android.kotlin.multiplatform.library" }
ksp = { id = "com.google.devtools.ksp" }
metro = { id = "dev.zacsweers.metro" }
# Local convention plugins
projectkafka = { id = "io.github.shadowrz.projectkafka" }
projectkafka-application = { id = "io.github.shadowrz.projectkafka.application" }
projectkafka-compose = { id = "io.github.shadowrz.projectkafka.compose" }
projectkafka-feature = { id = "io.github.shadowrz.projectkafka.feature" }
projectkafka-glance = { id = "io.github.shadowrz.projectkafka.glance" }
projectkafka-kotest = { id = "io.github.shadowrz.projectkafka.kotest" }
projectkafka-library = { id = "io.github.shadowrz.projectkafka.library" }
projectkafka-library-jvm = { id = "io.github.shadowrz.projectkafka.jvm-library" }
projectkafka-multiplatform = { id = "io.github.shadowrz.projectkafka.multiplatform" }
# Others
aboutlibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutlibraries" }
buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }
compose-hotreload = { id = "org.jetbrains.compose.hot-reload", version.ref = "compose-hot-reload"}
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }
