[versions]
aboutlibraries = "13.1.0"
accompanist = "0.37.3"
activity = "1.11.0"
agp = "8.13.0"
androidx-annotation = "1.9.1"
appcompat = "1.7.1"
browser = "1.9.0"
circuit = "0.31.0"
coil = "3.3.0"
compose-bom = "2025.11.00"
compose-multiplatform = "1.9.3"
compose-unstyled = "1.47.2"
constraintlayout-compose = "1.1.1"
core-ktx = "1.17.0"
datastore = "1.1.7"
decompose = "3.4.0"
dependency-analysis = "3.4.1"
desugar = "2.1.5"
detekt = "1.23.8"
detekt-compose = "0.4.27"
emoji2 = "1.6.0"
espresso-core = "3.7.0"
essenty = "2.5.0"
glance = "1.1.1"
hanekokoro-framework = "0.1.0"
junit = "4.13.2"
junit-android = "1.3.0"
kotest = "6.0.4"
kotlin = "2.2.21"
kotlinpoet = "2.2.0"
kotlinx-coroutines = "1.10.2"
kotlinx-datetime = "0.7.1"
kotlinx-serialization = "1.9.0"
krop = "0.2.0"
ksp = "2.3.0"
ktlint-gradle = "13.1.0"
material3 = "1.5.0-alpha08"
material3-adaptive = "1.2.0"
metro = "0.7.5"
molecule = "2.2.0"
okio = "3.16.2"
paging = "3.3.6"
preference = "1.2.1"
requery-sqlite = "3.49.0"
robolectric = "4.16"
sharetarget = "1.2.0"
splashscreen = "1.2.0"
sqldelight = "2.2.1"
startup = "1.2.0"
test = "1.7.0"
timber = "5.0.1"
turbine = "1.2.1"
uri = "0.0.21"

[libraries]
aboutlibraries-compose-material3 = { group = "com.mikepenz", name = "aboutlibraries-compose-m3", version.ref = "aboutlibraries" }
aboutlibraries-core = { group = "com.mikepenz", name = "aboutlibraries-core", version.ref = "aboutlibraries" }
accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity" }
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "androidx-annotation" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-browser = { group = "androidx.browser", name = "browser", version.ref = "browser" }
androidx-compose-annotation = { group = "androidx.compose.runtime", name = "runtime-annotation" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
androidx-compose-runtime-saveable = { group = "androidx.compose.runtime", name = "runtime-saveable" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "constraintlayout-compose" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
androidx-emojipicker = { group = "androidx.emoji2", name = "emoji2-emojipicker", version.ref = "emoji2" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
androidx-glance = { group = "androidx.glance", name = "glance", version.ref = "glance" }
androidx-glance-appwidget = { group = "androidx.glance", name = "glance-appwidget", version.ref = "glance" }
androidx-glance-appwidget-preview = { group = "androidx.glance", name = "glance-appwidget-preview", version.ref = "glance" }
androidx-glance-material3 = { group = "androidx.glance", name = "glance-material3", version.ref = "glance" }
androidx-glance-preview = { group = "androidx.glance", name = "glance-preview", version.ref = "glance" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit-android" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-material3-adaptive = { group = "androidx.compose.material3.adaptive", name = "adaptive", version.ref = "material3-adaptive" }
androidx-paging-common = { group = "androidx.paging", name = "paging-common", version.ref = "paging" }
androidx-paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "paging" }
androidx-preference = { group = "androidx.preference", name = "preference", version.ref = "preference" }
androidx-sharetarget = { group = "androidx.sharetarget", name = "sharetarget", version.ref = "sharetarget" }
androidx-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "splashscreen" }
androidx-startup = { group = "androidx.startup", name = "startup-runtime", version.ref = "startup" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "test" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "test" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
circuit-sharedelements = { group = "com.slack.circuit", name = "circuit-sharedelements", version.ref = "circuit" }
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-gif = { group = "io.coil-kt.coil3", name = "coil-gif", version.ref = "coil" }
composables-core = { group = "com.composables", name = "core", version.ref = "compose-unstyled" }
decompose = { group = "com.arkivanov.decompose", name = "decompose", version.ref = "decompose" }
decompose-compose = { group = "com.arkivanov.decompose", name = "extensions-compose", version.ref = "decompose" }
decompose-compose-experimental = { group = "com.arkivanov.decompose", name = "extensions-compose-experimental", version.ref = "decompose" }
decompose-jetpack = { group = "com.arkivanov.decompose", name = "jetpack-component-context", version.ref = "decompose" }
desugar = { group = "com.android.tools", name = "desugar_jdk_libs_nio", version.ref = "desugar" }
detekt-compose = { group = "io.nlopez.compose.rules", name = "detekt", version.ref = "detekt-compose" }
essenty-backhandler = { group = "com.arkivanov.essenty", name = "back-handler", version.ref = "essenty" }
essenty-coroutines = { group = "com.arkivanov.essenty", name = "lifecycle-coroutines", version.ref = "essenty" }
hanekokoro-framework-annotations = { group = "io.github.shadowrz.hanekokoro.framework", name = "annotations", version.ref = "hanekokoro-framework" }
hanekokoro-framework-codegen = { group = "io.github.shadowrz.hanekokoro.framework", name = "codegen", version.ref = "hanekokoro-framework" }
hanekokoro-framework-runtime = { group = "io.github.shadowrz.hanekokoro.framework", name = "runtime", version.ref = "hanekokoro-framework" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
kotest-assertions = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
kotlinpoet = { group = "com.squareup", name = "kotlinpoet", version.ref = "kotlinpoet" }
kotlinpoet-ksp = { group = "com.squareup", name = "kotlinpoet-ksp", version.ref = "kotlinpoet" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-serialization-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
krop-core = { group = "com.attafitamim.krop", name = "core", version.ref = "krop" }
ksp-api = { group = "com.google.devtools.ksp", name = "symbol-processing-api", version.ref = "ksp" }
metro-runtime = { group = "dev.zacsweers.metro", name = "runtime", version.ref = "metro" }
molecule-runtime = { group = "app.cash.molecule", name = "molecule-runtime", version.ref = "molecule" }
okio = { group = "com.squareup.okio", name = "okio", version.ref = "okio" }
okio-fakefilesystem = { group = "com.squareup.okio", name = "okio-fakefilesystem", version.ref = "okio" }
requery-sqlite = { group = "com.github.requery", name = "sqlite-android", version.ref = "requery-sqlite" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
sqldelight-android = { group = "app.cash.sqldelight", name = "android-driver", version.ref = "sqldelight" }
sqldelight-coroutines = { group = "app.cash.sqldelight", name = "coroutines-extensions", version.ref = "sqldelight" }
sqldelight-jvm = { group = "app.cash.sqldelight", name = "sqlite-driver", version.ref = "sqldelight" }
sqldelight-paging = { group = "app.cash.sqldelight", name = "androidx-paging3-extensions", version.ref = "sqldelight" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }
uri = { group = "com.eygraber", name = "uri-kmp", version.ref = "uri" }

# Convention plugins dependencies
android-gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
compose-compiler-plugin = { group = "org.jetbrains.kotlin", name = "compose-compiler-gradle-plugin", version.ref = "kotlin" }
compose-multiplatform-plugin = { group = "org.jetbrains.compose", name = "org.jetbrains.compose.gradle.plugin", version.ref = "compose-multiplatform" }
dependencyanalysis-plugin = { group = "com.autonomousapps.dependency-analysis", name = "com.autonomousapps.dependency-analysis.gradle.plugin", version.ref = "dependency-analysis" }
detekt-plugin = { group = "io.gitlab.arturbosch.detekt", name = "io.gitlab.arturbosch.detekt.gradle.plugin", version.ref = "detekt" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-parcelize-plugin = { group = "org.jetbrains.kotlin.plugin.parcelize", name = "org.jetbrains.kotlin.plugin.parcelize.gradle.plugin", version.ref = "kotlin" }
ksp-plugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
ktlint-plugin = { group = "org.jlleitschuh.gradle.ktlint", name = "org.jlleitschuh.gradle.ktlint.gradle.plugin", version.ref = "ktlint-gradle" }
metro-gradle-plugin = { group = "dev.zacsweers.metro", name = "dev.zacsweers.metro.gradle.plugin", version.ref = "metro" }

[plugins]
aboutlibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutlibraries" }
aboutlibraries-android = { id = "com.mikepenz.aboutlibraries.plugin.android", version.ref = "aboutlibraries" }
android-application = { id = "com.android.application", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
dependencyanalysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependency-analysis" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }
