name: Build Release APKs

on:
  workflow_dispatch:
  push:
    tags: [ "v*" ]

env:
  CI_GRADLE_ARG_PROPERTIES: "--stacktrace"

permissions: {}

jobs:
  build:
    name: Build Release APKs
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ format('release-{0}', github.ref)  }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Configure Gradle
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0
        with:
          cache-disabled: true
      - name: Export AboutLibraries library definitions
        run: ./gradlew :app:exportLibraryDefinitions --dependency-verification lenient --continue $CI_GRADLE_ARG_PROPERTIES
      - name: Assemble release APKs
        run: ./gradlew :app:assembleRelease $CI_GRADLE_ARG_PROPERTIES
      - name: Upload release APKs
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: projectkafka-release-apk
          path: |
            app/build/outputs/apk/release/*-release-unsigned.apk
      - name: Assemble release AAB
        run: ./gradlew :app:bundleRelease $CI_GRADLE_ARG_PROPERTIES
      - name: Upload release AAB
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: projectkafka-release-aab
          path: |
             app/build/outputs/bundle/release/*-release.aab
